version: 2.1

jobs:
  # create_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Ensure backend infrastructure exist
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name my-stack
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["e6:72:b7:d4:aa:4e:75:28:b9:85:e6:c7:41:61:82:af:74:42:17:bb"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main.yml
workflows:
  my_workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure