version: 2.1

jobs:
  # create_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Ensure backend infrastructure exist
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name my-stack
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c3:14:9a:30:4e:9e:54:60:8d:8f:b0:21:02:b7:33:e8"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main.yml
workflows:
  my_workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure