version: 2.1

parameters:
  stack-name: 
    type: string
    default: "my-stack"

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name << pipeline.parameters.stack-name >>
  configure_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "4c:a2:f6:27:8f:f6:cf:71:7a:66:dd:ad:5a:cf:5d:55"
      - run:
          name: Install dependencies
          command: |
            yum install -y python3
            yum install -y ansible
      - run:
          name: Add EC2 instance ip to inventory
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> inventory
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main.yml
  # delete_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - run:
  #         name: Delete infrastructure
  #         command: |
  #           aws cloudformation delete-stack --region=eu-central-1 --stack-name << pipeline.parameters.stack-name >>
workflows:
  my_workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
          # requires:
          #   - create_infrastructure
      # - delete_infrastructure:
      #     requires:
      #       - configure_infrastructure